#ifndef __BSP_GPIO_H
#define __BSP_GPIO_H
#include "bsp.h"
#define BLE_PWR_PORT		GPIOC
#define BLE_PWR_PIN			LL_GPIO_PIN_9

#define LED_PWR_PORT		GPIOC
#define LED_PWR_PIN		LL_GPIO_PIN_12


#define LED_ROW_PORT		GPIOA
#define LED_ROW1_PIN		LL_GPIO_PIN_1
#define LED_ROW2_PIN		LL_GPIO_PIN_2
#define LED_ROW3_PIN		LL_GPIO_PIN_3
#define LED_ROW4_PIN		LL_GPIO_PIN_4
#define LED_ROW5_PIN		LL_GPIO_PIN_8
#define LED_ROW6_PIN		LL_GPIO_PIN_15

#define LED_ROW_ALL_PIN		(LL_GPIO_PIN_1|LL_GPIO_PIN_2|LL_GPIO_PIN_3|LL_GPIO_PIN_4|LL_GPIO_PIN_8|LL_GPIO_PIN_15)

// #define LED_ROW1_ON()		LL_GPIO_ResetOutputPin(LED_ROW_PORT,LED_ROW1_PIN);
// #define LED_ROW2_ON()		LL_GPIO_ResetOutputPin(LED_ROW_PORT,LED_ROW2_PIN);
// #define LED_ROW3_ON()		LL_GPIO_ResetOutputPin(LED_ROW_PORT,LED_ROW3_PIN);
// #define LED_ROW4_ON()		LL_GPIO_ResetOutputPin(LED_ROW_PORT,LED_ROW4_PIN);
// #define LED_ROW5_ON()		LL_GPIO_ResetOutputPin(LED_ROW_PORT,LED_ROW5_PIN);
// #define LED_ROW6_ON()		LL_GPIO_ResetOutputPin(LED_ROW_PORT,LED_ROW6_PIN);
/*****一个很奇怪的问题，先或再与就正常，否则不正常********/
//低电平为ON
#define LED_ALL_ROW_OFF()	LED_ROW_PORT->ODR = (LED_ROW_PORT->ODR) | LED_ROW_ALL_PIN
#define LED_ALL_ROW_ON()	LED_ROW_PORT->ODR = (LED_ROW_PORT->ODR) & (~LED_ROW_ALL_PIN)
#define LED_ROW1_ON()		LED_ROW_PORT->ODR = ((LED_ROW_PORT->ODR | LED_ROW_ALL_PIN) & (~LED_ROW1_PIN))
#define LED_ROW2_ON()		LED_ROW_PORT->ODR = ((LED_ROW_PORT->ODR | LED_ROW_ALL_PIN) & (~LED_ROW2_PIN))
#define LED_ROW3_ON()		LED_ROW_PORT->ODR = ((LED_ROW_PORT->ODR | LED_ROW_ALL_PIN) & (~LED_ROW3_PIN))
#define LED_ROW4_ON()		LED_ROW_PORT->ODR = ((LED_ROW_PORT->ODR | LED_ROW_ALL_PIN) & (~LED_ROW4_PIN))
#define LED_ROW5_ON()		LED_ROW_PORT->ODR = ((LED_ROW_PORT->ODR | LED_ROW_ALL_PIN) & (~LED_ROW5_PIN))
#define LED_ROW6_ON()		LED_ROW_PORT->ODR = ((LED_ROW_PORT->ODR | LED_ROW_ALL_PIN) & (~LED_ROW6_PIN))



#define KEY_ROW_PORT		GPIOC
#define KEY_ROW1_PIN		LL_GPIO_PIN_1
#define KEY_ROW2_PIN		LL_GPIO_PIN_2
#define KEY_ROW3_PIN		LL_GPIO_PIN_3
#define KEY_ROW4_PIN		LL_GPIO_PIN_4
#define KEY_ROW5_PIN		LL_GPIO_PIN_5
#define KEY_ROW6_PIN		LL_GPIO_PIN_6
#define KEY_ROW_ALL_PIN		(LL_GPIO_PIN_1|LL_GPIO_PIN_2|LL_GPIO_PIN_3|LL_GPIO_PIN_4|LL_GPIO_PIN_5|LL_GPIO_PIN_6)

//高电平为ON
#define KEY_ALL_ROW_UNSELECT()	KEY_ROW_PORT->ODR = (KEY_ROW_PORT->ODR) & (~KEY_ROW_ALL_PIN) 
#define KEY_ALL_ROW_SELECT()	KEY_ROW_PORT->ODR = (KEY_ROW_PORT->ODR) | KEY_ROW_ALL_PIN
#define KEY_ROW1_SELECT()		KEY_ROW_PORT->ODR = ((KEY_ROW_PORT->ODR & (~KEY_ROW_ALL_PIN)) | KEY_ROW1_PIN)
#define KEY_ROW2_SELECT()		KEY_ROW_PORT->ODR = ((KEY_ROW_PORT->ODR & (~KEY_ROW_ALL_PIN)) | KEY_ROW2_PIN)
#define KEY_ROW3_SELECT()		KEY_ROW_PORT->ODR = ((KEY_ROW_PORT->ODR & (~KEY_ROW_ALL_PIN)) | KEY_ROW3_PIN)
#define KEY_ROW4_SELECT()		KEY_ROW_PORT->ODR = ((KEY_ROW_PORT->ODR & (~KEY_ROW_ALL_PIN)) | KEY_ROW4_PIN)
#define KEY_ROW5_SELECT()		KEY_ROW_PORT->ODR = ((KEY_ROW_PORT->ODR & (~KEY_ROW_ALL_PIN)) | KEY_ROW5_PIN)
#define KEY_ROW6_SELECT()		KEY_ROW_PORT->ODR = ((KEY_ROW_PORT->ODR & (~KEY_ROW_ALL_PIN)) | KEY_ROW6_PIN)




#define KEY_COL_PORT		GPIOB
#define KEY_COL_ALL_PIN 		LL_GPIO_PIN_ALL
#define KEY_COL1_PIN			LL_GPIO_PIN_0

void bsp_Init_GPIO(void);
void GPIO_BLE_Power(uint8_t state);
void GPIO_LED_Power(uint8_t state);
void GPIO_Config_EXTI(void);
#endif
